[package]
name = "mecha-led"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Dhruvesh08/mecha-led"
homepage = "https://github.com/Dhruvesh08/mecha-led"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
